title:            프레시안 개발자 센터
description:      프레시안 개발자 센터
url:              http://pressian.github.io/
signoff:          열린 프레시안
google_analytics: UA-61936757-1

links:
  - name:         Blog
    url:          http://openpressian.wordpress.com/
    external:      true
  - name:         Playground
    url:          http://pressian.github.io/playground/
    external:     true
  - name:         Newsletter
    url:          http://eepurl.com/baX51v
    external:     true
  - name:         Documents
    url:          http://github.com/pressian/docs/
    external:     true
  - name:         GitHub
    url:          http://github.com/pressian
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         kramdown
