title:            프레시안 개발자 센터
description:      프레시안 개발자 센터
url:              http://developers.pressian.coop
signoff:          Open Pressian

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog
  - name:         Newsletter
    url:          /newsletter
  - name:         Wiki
    url:          http://pressian.atlassian.net/wiki/
    external:     true
  - name:         GitHub
    url:          http://github.com/pressian
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
