title:            프레시안 개발자 센터
description:      프레시안 개발자 센터
url:              http://developers.pressian.coop
signoff:          Open Pressian
google_analytics: UA-61936757-1

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /blog
  - name:         Newsletter
    url:          /newsletter
  - name:         Documents
    url:          http://github.com/pressian/docs/
    external:     true
  - name:         Playground
    url:          /playground/
  - name:         GitHub
    url:          http://github.com/pressian
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         kramdown
